# Generated by Django 3.1.7 on 2021-04-07 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_product'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='Produto',
        ),
    ]
