# Generated by Django 3.1.7 on 2021-04-07 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_auto_20210407_0002'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='Cliente',
        ),
    ]
